name: gitignored-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [20]
                threads: [4]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install Depedencies
              run: pnpm i

            - name: Install Puppeteer
              run: node node_modules/puppeteer/install.mjs

            - name: Env
              run: make copy-env-testing

            - name: Start Database
              run: make start-testing-database

            - name: Run Sql Migration
              run: make migrate-up

            - name: Generate Type Definitions
              run: make generate-typesafe-environment

            - name: Generate Database Type Definitions
              run: make generate-local-database-type

            - name: Lint code
              run: make lint

            - name: Typecheck code
              run: make typecheck

            - name: Format Check
              run: make format-check

            - name: Test
              run: make test
