name: gitignored-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install and Setup MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: 5.0
              run: make setup-mongo

            - name: Install Depedencies
              env:
                  NODE_ENV: development
              run: make install

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  MONGO_DB: testGitignored
                  MONGO_COLLECTION_TECH: tech
                  MONGO_COLLECTION_TIMESTAMP: timestamp
                  MONGO_USER: runner
                  MONGO_PASSWORD: mongodb
                  MONGO_ADDRESS: localhost
                  MONGO_PORT: 27017
                  NODE_ENV: test
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              env:
                  NODE_ENV: production
              run: make build
