name: gitignored-ci-cd

on: [push, pull_request]

env:
    IS_CI: true

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install PNPM
              run: |
                  sudo apt install npm
                  npm i --location=global pnpm@8

            - name: Install Depedencies
              run: make install

            - name: Install MongoDB
              run: make install-mongo

            - name: Start MongoDB
              run: make start-mongo

            - name: Migrate Document
              run: |
                  sleep 5
                  make migrate-mongo

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  MONGO_DB: testGitignored
                  MONGO_COLLECTION_TECH: tech
                  MONGO_COLLECTION_UPDATE_TIME: updatetime
                  MONGO_USER: runner
                  MONGO_PASSWORD: mongodb
                  MONGO_ADDRESS: localhost
                  MONGO_PORT: 27017
                  NODE_ENV: test
              run: make test

            - name: Run Build
              env:
                  NODE_ENV: production
              run: make build
