name: gitignore-cli-ci-cd

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        threads:
          - "4"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        run: make install-rust

      - name: Install PNPM & Node
        run: |
          sudo apt-get install npm
          sudo apt-get install nodejs
          npm install --location=global pnpm

      - name: Install Dependencies
        run: make install

      - name: Run Code Generator
        run: make pre-prod

      - name: Run Linter
        run: make lint

      - name: Run Code Check
        run: make check

      - name: Run Format Check
        run: make format-check

      - name: Run Tests
        run: make test-prod

      - name: Run Build
        run: make build
