name: gitignored-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Depedencies
              env:
                  MONGO_DB: db
                  MONGO_COLkECTION_TECH: tech
                  MONGO_COLLECTION_TIMESTAMP: timestamp
                  MONGO_ADDRESS: address
                  MONGO_SRV: srv
                  MONGO_USER: user
                  MONGO_PASSWORD: password
                  NODE_ENV: development
              run: yarn

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Build
              env:
                  MONGO_DB: db
                  MONGO_COLkECTION_TECH: tech
                  MONGO_COLLECTION_TIMESTAMP: timestamp
                  MONGO_ADDRESS: address
                  MONGO_SRV: srv
                  MONGO_USER: user
                  MONGO_PASSWORD: password
                  NODE_ENV: production
              run: make build
