name: gitignored-ci

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [20]
                threads: [4]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install Depedencies
              run: pnpm i

            # root
            - name: Generate Types
              run: pnpm generate-type-for-ci

            - name: Run Format Check
              run: pnpm format-check

            - name: Run Linter
              run: pnpm lint

            - name: Run Type Check
              run: pnpm typecheck

            - name: Run Test
              run: pnpm test

            # cli
            - name: Run Cli Build
              working-directory: apps/cli
              run: make build

            - name: Run Cli Package
              working-directory: apps/cli
              run: make package argv="-l --allow-dirty"

            - name: Run Cli Publish Dry Run
              working-directory: apps/cli
              run: make publish argv="--dry-run --allow-dirty"
